### PR TITLE
Added period, description sorted errors.

### PR DESCRIPTION
**Pull request by Shashankzz0007**
Added period and added description in roles as requested.

closes #ISSUE-NO

### CODE REVIEW

**Comment by Shashankzz0007** [comment]
Hey community members please review this PR thank you.

**Review by Panquesito7 — APPROVED** [review]
Looks good to me! 🚀

**Comment by Shashankzz0007** [comment]
Thank @Panquesito7 for reviewing. Have great day.

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

**Pull request merged**
