### PR TITLE
docs(discord-readme): improved content

### PR DESCRIPTION
**Pull request by YayoKB**
Removed deleted channels, ALERTS section (no publicly available channels), added/removed punctuation where necessary, fixed discord-readme.md link (old URL directed to 404 page), added viewable emojis

### CODE REVIEW

**Comment by schmelto** [comment]
There is a linter error 
```
./docs/discord/discord-readme.md:100 MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Roles"]

```

**Comment by YayoKB** [comment]
> There is a linter error
> 
> ```
> ./docs/discord/discord-readme.md:100 MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Roles"]
> ```

Okay, I've changed the ``**Roles**`` heading to ``## Roles``. This passes the lint check. Is it all good now?

**Review by eddiejaoude — APPROVED** [review]
Thank you for the improvements 👍

**Comment by eddiejaoude** [comment]
OMG @YayoKB did I forget to merge this 😱 sorry it slipped through the gaps. Are you ok to re-open it

I am so sorry to have missed this, please nudge us in Discord if we don't reply after a few days

**Comment by YayoKB** [comment]
oh oops LOL no worries! @eddiejaoude yeah of course i'll re-open it :))

**Comment by eddiejaoude** [comment]
Thank you @YayoKB

**Pull request merged**
