### PR TITLE
Favicon Update

### LINKED ISSUE #4920: [FEATURE REQUEST] Adding favicon to the title bar
### Description of feature request, idea

Adding logo of eddiehub to the title bar would be more engaging to the viewers. So, I got this idea of adding it. And this is my first issue raising in eddiehub organization. Looking forward to work :)

### Add (multiple) screenshot links (if applicable)

image

### Add any other context about the feature request here

_No response_

### PR DESCRIPTION
**Pull request by keerthana054**
closes #4920

#### What does this PR do?
This PR is update of Favicon in title bar.
#### Description of the task to be completed?
Adding logo of eddiehub to the title bar would be more engaging to the viewers.
#### Is there any relevant issue to this PR?
No, I didn't find any related to this
#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by schmelto — COMMENTED** [review]
I'm not sure weather the aspect ratio of the favicon / logo is right 🤔 it seems to be a little bit stretched.

**Comment by keerthana054** [comment]
> I'm not sure weather the aspect ratio of the favicon / logo is right 🤔 it seems to be a little bit stretched.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Let me check it sir and update soon!

**Comment by keerthana054** [comment]
I've updated it sir! 
image

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by SaptarshiSarkar12 — APPROVED** [review]
This code looks good to me. It can be merged. 👍

**Review by SamiShaikh6810 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Awesome! Thanks. 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

**Review by RealSollyM — APPROVED** [review]
This update looks great. It can be merged.

**Comment by keerthana054** [comment]
> This update looks great. It can be merged.

Can this PR be considered for hactoberfest?!

**Comment by krshkodes** [comment]
@keerthana054 only PRs created after october 1st are counted for hacktoberfest

**Review by krshkodes — APPROVED** [review]

**Pull request merged**
