### PR TITLE
[feat/fix]: Improve the issue templates

### PR DESCRIPTION
**Pull request by Panquesito7**
#### What does this PR do?

- Improve the issue templates.

#### Description of the task to be completed?

None.

#### How can this be manually tested?

This would have to be merged to `master` to see if it works properly, or we can check the templates in my [fork](https://github.com/Panquesito7/support/tree/improve_issue_templates/.github/ISSUE_TEMPLATE). 🙂

#### Any background context you want to provide?

Nope.

#### Is there any relevant issue to this PR?

#2026, #2002, #1952, 

#### Questions

None.

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
Lgtm

**Comment by schmelto** [comment]
Would you like also to adjust the 'our' in the join the Discord server?

**Review by krishdevdb — DISMISSED** [review]
LGMT 🚀

**Comment by Panquesito7** [comment]
> Would you like also to adjust the 'our' in the join the Discord server?

Sure, will do. 🙂

**Review by schmelto — APPROVED** [review]

**Pull request merged**
