### PR TITLE
[DOCS] Spelling email #4887 Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by sree-hari-s**
changed e-mail to email

closes #ISSUE-NO

#### What does this PR do?
[DOCS] Spelling email #4887

### CODE REVIEW

**Comment by adisuyash** [comment]
E-mail or email both are correct. But I searched it on Google and here's what I found :

image

Try to contribute to some other [Issues](https://github.com/EddieHubCommunity/support/issues)✨

**Comment by sree-hari-s** [comment]
@adisuyash I saw a [#8073](https://github.com/EddieHubCommunity/support/pull/8073#pullrequestreview-1589110653), And did the changes.

**Comment by adisuyash** [comment]
> @adisuyash I saw a [#8073](https://github.com/EddieHubCommunity/support/pull/8073#pullrequestreview-1589110653), And did the changes.

Yes there are issues ( #8073 #8082 #4887 ) regarding this but no one was required to do the change. Also no one assigns you to resolve this issue 

It is a better practice to get assigned first, then create a Pull Request regarding that issue. Thank You

**Comment by Anjalisharma3463** [comment]
> > @adisuyash I saw a [#8073](https://github.com/EddieHubCommunity/support/pull/8073#pullrequestreview-1589110653), And did the changes.
> 
> Yes there are issues ( #8073 #8082 #4887 ) regarding this but no one was required to do the change. Also no one assigns you to resolve this issue
> 
> It is a better practice to get assigned first, then create a Pull Request regarding that issue. Thank You

can you please explain ? what do you mean by assigned first ? actually im new to github

**Comment by sree-hari-s** [comment]
When you find an issue you can resolve, you need to ask the maintainers to assign it to you before working on it.

**Pull request closed without merging**
