### PR TITLE
Update bug.md

### PR DESCRIPTION
**Pull request by sri32jan**
closes #ISSUE-NO

### CODE REVIEW

**Comment by starlightknown** [comment]
For which issue is this PR for? I see only a space added here which is not needed

**Comment by schmelto** [comment]
Hey @sri32jan , thanks for raising this PR but I think the space here is not needed.
What is you intention behind this change?

**Comment by schmelto** [comment]
> For which issue is this PR for? I see only a space added here which is not needed

oh you were faster then me lol 🤣

**Comment by starlightknown** [comment]
Oh it's alright, I don't see there's need of the change right now, you can practice more on hacktober fest repository and even join us on discord so that you can get started with GitHub and opensource. We'll be glad to have you. You can close this PR for now. Thank you

**Pull request closed without merging**
