### PR TITLE
Added gh-profile-review-md

### LINKED ISSUE #1179: Make additional ISSUE_TEMPLATES for open source reviews
# Idea
I think we should create separate issue templates for:
- `GH Profile review`
- `Open Source Project review`
- `Portfolio review`
- `Resume review`

# Reason
This is to encourage people to send one link per issue so @eddiejaoude doesn't have to choose to review one out of two or three. For example when @eddiejaoude does a live stream for specific reviews - it'll be easier for him to filter out the specific type of reviews he is doing on that day.

# How to do it?
Just `copy&paste` this file -> `.github/ISSUE_TEMPLATE/resume-review.md` and rather writing this:
```
Items we can review on a live stream:

-> GitHub profile
-> Open source project
-> Portfolio
-> Resume
```

... write this:
```
Please review my {GitHub profile (for example)}: <insert link here>
```

# TODO List

- [x] `GH Profile review`
- [x] `Open Source Project review`
- [x] `Portfolio review`
- [x] `Resume review`

### PR DESCRIPTION
**Pull request by jainaayush01**
#### What does this PR do?
It adds the GitHub profile review issue template to review it on Livestream

### CODE REVIEW

**Comment by jainaayush01** [comment]
image
It's working fine you can also have a look at my forked repo:
https://github.com/jainaayush01/support/issues/new/choose

please let me know if there's something more to add.
Thank you for the support

**Review by SashoStoichkov — APPROVED** [review]
LGTM 👍🏻

**Comment by SashoStoichkov** [comment]
@jainaayush01 please delete `closes #1179` because that PR won't close the issue 😉

**Review by SamDev98 — COMMENTED** [review]
Heres what i think:
1. I think the title can be kept empty.
2. The label used here has no description, be good if there was one.

Beside this, the PR LGTM.

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Yep, the title should be empty.

**Comment by SashoStoichkov** [comment]
@SamDev98 @vinzvinci - @nhcarrigan suggested to have heading in the title. Also it'll be easier to stand out with this heading.

**Comment by vinzvinci** [comment]
Ahh I see. Thanks

**Comment by SamDev98** [comment]
@SashoStoichkov Alright, just a question then, shouldn't this change be reflected in all the templates to keep it homogeneous? Others have no title, this could be a separate issue/PR though.

**Review by SamDev98 — APPROVED** [review]
Besides the comments, the PR looks good.

**Comment by SashoStoichkov** [comment]
@SamDev98 I think it'll be good to add this to the other issue templates as well 😉

**Comment by jainaayush01** [comment]
if there any changes to be done, please let me know.

**Review by nhcarrigan — APPROVED** [review]
This looks good to me.

**Comment by jainaayush01** [comment]
Yay, Sure I will watch out on them.

**Pull request merged**
