### PR TITLE
docs: fix space issues and update issue type

### PR DESCRIPTION
**Pull request by schmelto**

### CODE REVIEW

**Review by starlightknown — DISMISSED** [review]
LGTM but shall I close my PR now? You have done all changes in this one right?

**Comment by schmelto** [comment]
> LGTM but shall I close my PR now? You have done all changes in this one right?

Oh sorry I forgot that you also have opened a pr I will remove the conflicting line 🙈

**Comment by schmelto** [comment]
removing discord link update due duplicate with https://github.com/EddieHubCommunity/support/pull/1580

**Comment by schmelto** [comment]
> Looks good, the order now might be merging the PR #1580 and then this right? 

I think those should not habe a merge conflict now but I'm not sure lol

**Pull request closed without merging**
