### PR TITLE
Updated Discord and Youtube Links in Readme

### LINKED ISSUE #3686: [OTHER][DOCS] Update links at bottom of README
### What would you like to share?

# Proposed change
-On line 80 and 81 at the bottom of the README

## Discord Link Change
-Join our [Discord](http://discord.eddiehub.org) community. 

**or**

-Join our [Discord community](http://discord.eddiehub.org).

## Youtube Link Change
-Subscribe to our [YouTube](https://www.youtube.com/user/eddiejaoude) channel.

**or**

-Subscribe to our [YouTube channel](https://www.youtube.com/user/eddiejaoude).

### This is in order to make the links a little more concise and help the flow of the document.
-Please post your thoughts to this update below

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Nithin108**
closes #3686

### CODE REVIEW

**Comment by Nithin108** [comment]
I updated links for disord invite link and youtube  channel review my request and can merge it

**Review by schmelto — CHANGES_REQUESTED** [review]
The change from the issue is only for the text not the links maybe take a look back at the issue

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Review by jonatanlr98 — APPROVED** [review]

**Comment by eddiejaoude** [comment]
@jonatanlr98 do you need some help with GitHub? I suggest you join our EddieHub Discord and we can chat more about GitHub and open source there http://discord.eddiehub.org

**Review by krshdev — CHANGES_REQUESTED** [review]
Hi 👋 Can you relook at the issue once? The issue required some other changes, please revert these changes and do as requested in the issue. Thanks.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by ahmed82 — APPROVED** [review]
lgtm

**Comment by stemount** [comment]
These links were moved to the top in #4045 for better visibility, so this would add the links back to the footer, which is why they are conflicted.

**Comment by stemount** [comment]
Closing as there's PR duplication and this is an addition - nothing wrong with the changes! They are just not links right down at the bottom of the README.

**Pull request closed without merging**
