### PR TITLE
Change GitHub Action Texts

### LINKED ISSUE #853: Github action text on github mobile app
**Description**

Text is not formatted correctly on GitHub mobile app. 

**Working Environment**

Operating System: Android 

Device: Huawei P10 

**Screenshots**

[Optional] **Additional Context**

May we can change the text to `... Issue and welcome to... `

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

### PR DESCRIPTION
**Pull request by schmelto**
closes #853

#### What does this PR do?

Replace `!` with `...und...`

### CODE REVIEW

**Comment by AllanRegush** [comment]
I feel like if we just add a `\n` that would be better. But, I'm not sure if that works.

**Comment by eddiejaoude** [comment]
I think for line breaks it is html format, so `<br />` would work if needed

**Review by jcads — APPROVED** [review]

**Review by adityaraute — APPROVED** [review]
LGTM

**Comment by eddiejaoude** [comment]
Oops sorry forgot about this one. Thanks for the PR @schmelto and thanks @AllanRegush @jcads @adityaraute for reviewing and approving 👍

**Pull request merged**
