### PR TITLE
Created Open Source Review template

### PR DESCRIPTION
**Pull request by adityaraute**
Related to #1179 

#### What does this PR do?
Create an addition Issue Template

#### How can this be manually tested?
By creating the related issues

#### Any background context you want to provide?
Useful for differentiating during a live stream.

#### What is the relevant issue link?
https://github.com/EddieHubCommunity/support/issues/1179

### CODE REVIEW

**Review by AllanRegush — COMMENTED** [review]
Looks Good To Me :+1: I'll leave it up just in case the community notices anything! :smile:

**Review by BOLT04 — APPROVED** [review]
LGTM 👍, thank you @adityaraute 😃  
Just wondering, do we need to use this label ("open source review") for the open source project review?
imagem

**Comment by adityaraute** [comment]
I feel that would be the right way from now on, once we have all templates in place. @BOLT04

**Review by SashoStoichkov — APPROVED** [review]
Looks good to me

**Review by AllanRegush — APPROVED** [review]
:+1:

**Pull request merged**
