### PR TITLE
docs: add tip for squashing latest commit only

### PR DESCRIPTION
**Pull request by Panquesito7**
#### What does this PR do?

- Add a tip for squashing the latest commit only.
  - I think we might want to promote more these tips or add a link to them on our website: they're very useful. 🙂

#### How can this be manually tested?

I don't think this applies here unless we want to test the `git commit --amend` command. 😄

#### Any background context you want to provide?

Nope.

#### Is there any relevant issue to this PR?

Not that I know any.

#### Questions

None yet.

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
Not sure why the linter is failing. Its looking good for me.

**Comment by Panquesito7** [comment]
> Not sure why the linter is failing. Its looking good for me.

That happens when you have something in the middle between two points, and it thinks that you're not following the correct order. Not sure what could be the fix for that.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by Pradumnasaraf** [comment]
Hey @Panquesito7,

Please resolve the conflicts

**Comment by Panquesito7** [comment]
Done. I think the current warning can be fixed, but the order will be kinda messed up. 🤔

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
