### PR TITLE
feat: Disable blank issues

### PR DESCRIPTION
**Pull request by Panquesito7**
#### What does this PR do?

- Disables blank issues.
  - IMO, they should be removed as we already provide a lot of templates.

#### Description of the task to be completed?

None yet.

#### How can this be manually tested?

This can be tested by merging the PR and trying to create a blank issue. If it doesn't work, we can revert this PR.

#### Any background context you want to provide?

No.

#### Is there any relevant issue to this PR?

#2026

### CODE REVIEW

**Comment by schmelto** [comment]
I'm not a fan of disable blank issues 🙈

**Comment by Panquesito7** [comment]
> disable blank issues

Hmm, alright. Anyways, I think we should wait until what other members think about this. If many people say "no", then we can close this PR. Else, we can merge it. Still, that depends on what happens. Thanks anyways. 🙂

**Comment by schmelto** [comment]
> > disable blank issues
> 
> Hmm, alright. Anyways, I think we should wait until what other members think about this. If many people say "no", then we can close this PR. Else, we can merge it. Still, that depends on what happens. Thanks anyways. 🙂
> 

Yeah I think we should discuss this :) for me it is. We have a lot of issue forms with strict "rules" on what you can include in an issue so if there is something really special there should be an easy way to communicate those issues with a blank issue template. Also I think the blank issue template is not used that often.

**Comment by nhcarrigan** [comment]
I disable blank issues on my repositories (because I want the auto-labelling that comes with templates) but provide a very generic "other" template to use instead.

**Comment by schmelto** [comment]
> I disable blank issues on my repositories (because I want the auto-labelling that comes with templates) but provide a very generic "other" template to use instead.

I really like this idea 🚀

**Comment by Panquesito7** [comment]
> > I disable blank issues on my repositories (because I want the auto-labeling that comes with templates) but provide a very generic "other" template to use instead.
> 
> I really like this idea 🚀

Same. I think we should implement this. Should we implement it in this same PR or another PR?

**Comment by nhcarrigan** [comment]
It should be done in the same PR, to avoid potential disparity where blank issues are restricted but we do not have a corresponding template.

**Comment by Panquesito7** [comment]
> provide a very generic "other" template to use instead

Added now, thanks. 🙂

**Review by nhcarrigan — APPROVED** [review]
I think this is good. I'll let @eddiejaoude weigh in before merging though.

**Review by schmelto — APPROVED** [review]

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Review by deephunt3r — APPROVED** [review]
LGTM 💯

**Review by krishdevdb — APPROVED** [review]

**Comment by nhcarrigan** [comment]
Alright I'm going to merge. If

**Pull request merged**
