### PR TITLE
first pull request

### PR DESCRIPTION
**Pull request by deepanshu1334**
<

### CODE REVIEW

**Comment by deepanshu1334** [comment]
please merge this

**Review by schmelto — CHANGES_REQUESTED** [review]
I don't think those changes are needed here sue it seems that this is only a practice pr. feel free to grab on of our issues and create a pr for those.

**Review by lewisushindi — COMMENTED** [review]
was this necessary , really ? Visit the issue sections , look for an issue with the label good-first-issue or easy. Try to come up with solution of how you will resolve the issue, then you can pull a request indicating the issue number your have solved. Happy coding @deepanshu1334!

**Comment by Pradumnasaraf** [comment]
Changes are not necessary. The statement is already super clear. Closing this

**Pull request closed without merging**
