### PR TITLE
Added Additional info in GitHub Stars

### PR DESCRIPTION
**Pull request by Shashankzz0007**
Addition info was empty for GitHub Stars so I added the info.

closes #ISSUE-NO

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @Shashankzz0007! :) I hope you’re doing well! :) I found a few a grammatical errors in the description of GitHub Stars. For example, participants might wonder if “program” is starting the sentence since it’s in lowercase. Consider capitalizing it and putting the other words(Inspire, Educate, & Influence) in lowercase to clarify this point. My other suggestion is place commas in between the words I mentioned in parentheses. It’ll clarify to users that they are lists of qualities of GitHub stars. Lastly, add a period at the end of the sentence. It’ll let users know that the whole description is a complete sentence. If you have any questions or feedback on my review, feel free to tag me in your comment.

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @Shashankzz0007! :) I hope you’re doing well! :) I found a few a grammatical errors in the description of GitHub Stars. For example, participants might wonder if “program” is starting the sentence since it’s in lowercase. Consider capitalizing it and putting the other words(Inspire, Educate, & Influence) in lowercase to clarify this point. My other suggestion is place commas in between the words I mentioned in parentheses. It’ll clarify to users that they are lists of qualities of GitHub stars. Lastly, add a period at the end of the sentence. It’ll let users know that the whole description is a complete sentence. If you have any questions or feedback on my review, feel free to tag me in your comment.

**Comment by CBID2** [comment]
> Hi @Shashankzz0007! :) I hope you’re doing well! :) I found a few a grammatical errors in the description of GitHub Stars. For example, participants might wonder if “program” is starting the sentence since it’s in lowercase. Consider capitalizing it and putting the other words(Inspire, Educate, & Influence) in lowercase to clarify this point. My other suggestion is place commas in between the words I mentioned in parentheses. It’ll clarify to users that they are lists of qualities of GitHub stars. Lastly, add a period at the end of the sentence. It’ll let users know that the whole description is a complete sentence. If you have any questions or feedback on my review, feel free to tag me in your comment.

Ignore this one @Shashankzz0007

**Comment by Shashankzz0007** [comment]
@CBID2 sorry for being late here I will resolve the problems right away.

**Comment by CBID2** [comment]
> @CBID2 sorry for being late here I will resolve the problems right away.

You're good @Shashankzz0007! :) How was my feedback?

**Comment by Shashankzz0007** [comment]
@CBID2 it was great and you I am starting new in open source contribution so having hard time doing this figuring out things and talking with great community people, like yourself. Thanks for feedback.

**Pull request closed without merging**
