### PR TITLE
Create Finding-Open-Source-Projects.md

### PR DESCRIPTION
**Pull request by chryzcodez**
#958

#### What does this PR do?
Added finding open source projects into tips folder

### CODE REVIEW

**Comment by SashoStoichkov** [comment]
Duplicate with #958. Should be closed.
Thank you for the contribution 👍🏻

**Comment by chryzcodez** [comment]
> Duplicate with #973. Should be closed.
> Thank you for the contribution 👍🏻

Ok

**Comment by eddiejaoude** [comment]
Ah yes the file was already created https://github.com/EddieHubCommunity/support/blob/main/tips/finding-open-source-projects.md

Thank you though 👍 and you still get the 🟩

**Comment by chryzcodez** [comment]
> Ah yes the file was already created https://github.com/EddieHubCommunity/support/blob/main/tips/finding-open-source-projects.md
> 
> Thank you though 👍 and you still get the 🟩

Eddie I feel any issue that has been solved should be closed immediately!

**Comment by SashoStoichkov** [comment]
Every contribution adds value 👍🏻 And in opensource may happen that multiple people to work on a single issue. Than it's up to the maintainer to choose which PR to merge. That on the other hand depends on the amount of value added in the PR itself (description, title, etc)

As Eddie said - you still get the 🟩 for submitting the PR and it doesn't go away when said PR is closed

**Pull request closed without merging**
