### PR TITLE
fix: Use HTTPS instead in `youtube/generic.md`

### PR DESCRIPTION
**Pull request by Panquesito7**
#### What does this PR do?

- Use HTTPS instead in `youtube/generic.md`.

#### How can this be manually tested?

I don't think this applies here.

#### Any background context you want to provide?

Nope.

#### Is there any relevant issue to this PR?

AFAIK, no.

#### Questions

None.

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]
Awesome! Looks good!

**Comment by nhcarrigan** [comment]
Heya @Panquesito7,

This will need a rebase with the move to Docsify - let us know if you need help with that 🙂

**Review by schmelto — APPROVED** [review]
Lgtm

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm :rocket:

**Comment by Panquesito7** [comment]
Will re-create this PR as it's all messed up now. 😆

**Pull request closed without merging**
