### PR TITLE
updated the file with new name i.e EddieHub

### PR DESCRIPTION
**Pull request by bagladivyang03**
closes #ISSUE-NO

#### What does this PR do?
Updated the template with a new name i.e EddieHub

### CODE REVIEW

**Review by SashoStoichkov — APPROVED** [review]
Thank you 👍🏻 LGTM

**Comment by SashoStoichkov** [comment]
@bagladivyang03 #881

**Comment by bagladivyang03** [comment]
@SashoStoichkov Could u pls merge. It would be great :)

**Comment by SashoStoichkov** [comment]
Sorry, I don't have write access

**Comment by bagladivyang03** [comment]
ok np @SashoStoichkov

**Review by Nitesh-thapliyal — APPROVED** [review]
Looks good to me👍

**Review by Vyvy-vi — APPROVED** [review]
LGTM-! :+1: Thanks for the name change.

**Review by BOLT04 — COMMENTED** [review]
I think we should have these consistent, what do you think @bagladivyang03? What about we wait for feedback of @eddiejaoude on this [topic](https://github.com/EddieHubCommunity/support/pull/883#discussion_r571432439).

I'm indifferent, just think we should decide on one and be consistent 👍

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
Sorry for the delay everyone. This is a difficult one. I agree we should be consistent 👍 

I think `EddieHub` alone is enough (I know the GitHub Org is appended with `Community` because the name was taken)

**Pull request merged**
